import { City, Review, Meetup, Stats, Guide, PurposeRecommendation } from '@/types'

export const mockStats: Stats = {
  cities: 47,
  nomads: 1234,
  reviews: 3456,
  meetups: 89,
}

export const mockCities: City[] = [
  {
    id: '1',
    name: '제주시',
    region: '제주특별자치도',
    slug: 'jeju',
    thumbnail: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800&h=600&fit=crop',
    badge: 'popular',
    overallRating: 4.8,
    workRating: 4.9,
    costRating: 4.2,
    communityRating: 4.5,
    natureRating: 5.0,
    foodRating: 4.3,
    monthlyCost: 1800000,
    rentCost: 500000,
    cafeCost: 100000,
    internetSpeed: 500,
    currentTemp: 23,
    currentWeather: 'sunny',
    airQuality: 15,
    nomadCount: 324,
    reviewCount: 127,
    tags: ['카페천국', '힐링', '자연친화'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '2',
    name: '부산 해운대',
    region: '부산광역시',
    slug: 'busan-haeundae',
    thumbnail: 'https://images.unsplash.com/photo-1583037189850-1921ae7c6c22?w=800&h=600&fit=crop',
    badge: 'popular',
    overallRating: 4.6,
    workRating: 4.7,
    costRating: 4.1,
    communityRating: 4.6,
    natureRating: 4.5,
    foodRating: 4.8,
    monthlyCost: 1700000,
    rentCost: 480000,
    cafeCost: 95000,
    internetSpeed: 450,
    currentTemp: 18,
    currentWeather: 'cloudy',
    airQuality: 20,
    nomadCount: 289,
    reviewCount: 98,
    tags: ['해변', '맛집', '활기'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '3',
    name: '강릉',
    region: '강원도',
    slug: 'gangneung',
    thumbnail: 'https://images.unsplash.com/photo-1590470211991-26907d58ea6a?w=800&h=600&fit=crop',
    badge: 'rising',
    overallRating: 4.7,
    workRating: 4.8,
    costRating: 4.3,
    communityRating: 4.2,
    natureRating: 4.9,
    foodRating: 4.4,
    monthlyCost: 1600000,
    rentCost: 450000,
    cafeCost: 90000,
    internetSpeed: 400,
    currentTemp: 15,
    currentWeather: 'cloudy',
    airQuality: 12,
    nomadCount: 156,
    reviewCount: 76,
    tags: ['조용', '카페', '바다'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '4',
    name: '경주',
    region: '경상북도',
    slug: 'gyeongju',
    thumbnail: 'https://images.unsplash.com/photo-1625935217284-a16e9da58f2c?w=800&h=600&fit=crop',
    overallRating: 4.5,
    workRating: 4.6,
    costRating: 4.5,
    communityRating: 4.0,
    natureRating: 4.8,
    foodRating: 4.2,
    monthlyCost: 1500000,
    rentCost: 420000,
    cafeCost: 85000,
    internetSpeed: 380,
    currentTemp: 17,
    currentWeather: 'sunny',
    airQuality: 18,
    nomadCount: 98,
    reviewCount: 54,
    tags: ['역사', '문화', '조용'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '5',
    name: '전주',
    region: '전라북도',
    slug: 'jeonju',
    thumbnail: 'https://images.unsplash.com/photo-1578070181910-f1e514afdd08?w=800&h=600&fit=crop',
    overallRating: 4.4,
    workRating: 4.5,
    costRating: 4.6,
    communityRating: 4.3,
    natureRating: 4.2,
    foodRating: 4.9,
    monthlyCost: 1450000,
    rentCost: 400000,
    cafeCost: 80000,
    internetSpeed: 350,
    currentTemp: 19,
    currentWeather: 'sunny',
    airQuality: 22,
    nomadCount: 87,
    reviewCount: 62,
    tags: ['한옥', '맛집', '전통'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '6',
    name: '속초',
    region: '강원도',
    slug: 'sokcho',
    thumbnail: 'https://images.unsplash.com/photo-1517639493569-5666a7556f98?w=800&h=600&fit=crop',
    overallRating: 4.6,
    workRating: 4.4,
    costRating: 4.2,
    communityRating: 4.1,
    natureRating: 4.9,
    foodRating: 4.5,
    monthlyCost: 1650000,
    rentCost: 470000,
    cafeCost: 92000,
    internetSpeed: 390,
    currentTemp: 14,
    currentWeather: 'cloudy',
    airQuality: 14,
    nomadCount: 112,
    reviewCount: 48,
    tags: ['자연', '바다', '산'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '7',
    name: '여수',
    region: '전라남도',
    slug: 'yeosu',
    thumbnail: 'https://images.unsplash.com/photo-1619640961132-e34e46e3c7e8?w=800&h=600&fit=crop',
    overallRating: 4.5,
    workRating: 4.3,
    costRating: 4.4,
    communityRating: 4.2,
    natureRating: 4.8,
    foodRating: 4.6,
    monthlyCost: 1550000,
    rentCost: 440000,
    cafeCost: 88000,
    internetSpeed: 370,
    currentTemp: 20,
    currentWeather: 'sunny',
    airQuality: 16,
    nomadCount: 94,
    reviewCount: 41,
    tags: ['야경', '바다', '힐링'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '8',
    name: '춘천',
    region: '강원도',
    slug: 'chuncheon',
    thumbnail: 'https://images.unsplash.com/photo-1601894438743-58c49af5c8a0?w=800&h=600&fit=crop',
    overallRating: 4.3,
    workRating: 4.4,
    costRating: 4.5,
    communityRating: 4.1,
    natureRating: 4.6,
    foodRating: 4.3,
    monthlyCost: 1480000,
    rentCost: 410000,
    cafeCost: 82000,
    internetSpeed: 360,
    currentTemp: 16,
    currentWeather: 'cloudy',
    airQuality: 19,
    nomadCount: 76,
    reviewCount: 38,
    tags: ['호수', '자연', '조용'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '9',
    name: '대전',
    region: '대전광역시',
    slug: 'daejeon',
    thumbnail: 'https://images.unsplash.com/photo-1572358428949-78cd69f0e76f?w=800&h=600&fit=crop',
    overallRating: 4.4,
    workRating: 4.6,
    costRating: 4.3,
    communityRating: 4.3,
    natureRating: 4.1,
    foodRating: 4.4,
    monthlyCost: 1580000,
    rentCost: 450000,
    cafeCost: 87000,
    internetSpeed: 420,
    currentTemp: 18,
    currentWeather: 'sunny',
    airQuality: 24,
    nomadCount: 134,
    reviewCount: 56,
    tags: ['도시', '교통', '편리'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    id: '10',
    name: '통영',
    region: '경상남도',
    slug: 'tongyeong',
    thumbnail: 'https://images.unsplash.com/photo-1503457574462-bd27054394c1?w=800&h=600&fit=crop',
    overallRating: 4.6,
    workRating: 4.2,
    costRating: 4.3,
    communityRating: 3.9,
    natureRating: 5.0,
    foodRating: 4.7,
    monthlyCost: 1620000,
    rentCost: 460000,
    cafeCost: 89000,
    internetSpeed: 340,
    currentTemp: 19,
    currentWeather: 'sunny',
    airQuality: 13,
    nomadCount: 68,
    reviewCount: 34,
    tags: ['해안', '풍경', '조용'],
    createdAt: new Date(),
    updatedAt: new Date(),
  },
]

export const mockReviews: Review[] = [
  {
    id: '1',
    cityId: '1',
    cityName: '제주시',
    rating: 5,
    title: '제주는 정말 최고예요!',
    content: '3개월 동안 지냈는데 카페도 많고 인터넷도 빠르고 정말 좋았어요. 다시 오고 싶네요.',
    author: '노마드123',
    authorId: 'user1',
    helpfulCount: 24,
    commentCount: 5,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000), // 2일 전
  },
  {
    id: '2',
    cityId: '2',
    cityName: '부산 해운대',
    rating: 4,
    title: '부산 해운대 한달 살기 후기',
    content: '바다가 보이는 카페에서 작업하니 정말 힐링됐어요. 다만 여름에는 관광객이 너무 많아요.',
    author: '디지털유목민',
    authorId: 'user2',
    helpfulCount: 18,
    commentCount: 3,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000), // 5일 전
  },
  {
    id: '3',
    cityId: '3',
    cityName: '강릉',
    rating: 5,
    title: '조용하게 작업하기 딱 좋아요',
    content: '카페도 많고 분위기도 좋고 생활비도 저렴해서 장기 체류하기 좋습니다.',
    author: '프리랜서김',
    authorId: 'user3',
    helpfulCount: 15,
    commentCount: 2,
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000), // 7일 전
  },
]

export const mockMeetups: Meetup[] = [
  {
    id: '1',
    cityId: '1',
    cityName: '제주시',
    title: '제주 노마드 모임',
    date: new Date('2024-11-20T19:00:00'),
    attendeeCount: 12,
    maxAttendees: 20,
  },
  {
    id: '2',
    cityId: '2',
    cityName: '부산 해운대',
    title: '부산 디지털 노마드 네트워킹',
    date: new Date('2024-11-22T18:30:00'),
    attendeeCount: 8,
    maxAttendees: 15,
  },
  {
    id: '3',
    cityId: '3',
    cityName: '강릉',
    title: '강릉 워케이션 정보 공유',
    date: new Date('2024-11-25T19:00:00'),
    attendeeCount: 6,
    maxAttendees: 12,
  },
]

export const mockGuides: Guide[] = [
  {
    id: '1',
    icon: '📝',
    title: '첫 노마드 준비 완벽 가이드',
    description: '디지털 노마드 생활을 시작하기 위한 모든 것',
    link: '/guides/beginner',
  },
  {
    id: '2',
    icon: '💼',
    title: '원격근무 팁 베스트 10',
    description: '생산성을 높이는 원격근무 노하우',
    link: '/guides/remote-work',
  },
  {
    id: '3',
    icon: '🏠',
    title: '숙소 찾기 꿀팁 모음',
    description: '최적의 숙소를 찾는 검증된 방법들',
    link: '/guides/accommodation',
  },
]

export const mockPurposes: PurposeRecommendation[] = [
  {
    id: '1',
    icon: '💼',
    title: '집중 작업',
    description: '조용하고 카페가 많은 도시',
    cities: ['강릉', '경주', '춘천'],
  },
  {
    id: '2',
    icon: '🎉',
    title: '네트워킹',
    description: '활발한 커뮤니티와 밋업이 많은 곳',
    cities: ['서울', '부산', '제주'],
  },
  {
    id: '3',
    icon: '🏖️',
    title: '워케이션',
    description: '일과 휴양을 동시에!',
    cities: ['제주', '속초', '여수'],
  },
]
